name: monet_writer
description: "A minimalist novel writer app."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- 核心依赖 ---
  # 状态管理 (推荐使用较新稳定版)
  provider: ^6.1.2
  # 谷歌图标库
  cupertino_icons: ^1.0.6

  # --- 数据库 ---
  # Isar 数据库核心
  isar: ^3.1.0
  # Isar Flutter 适配库
  isar_flutter_libs: ^3.1.0
  # 获取本地文件路径 (文档目录等)
  path_provider: ^2.1.2

  # --- 文件操作 ---
  # 【关键修复】升级到 8.0.0+ 以解决 Android 编译报错
  # 用于选择本地字体文件 (.ttf/.otf)
  file_picker: ^8.0.0

  # --- 本地存储与媒体 ---
  # 轻量级键值对存储 (存昵称、设置开关)
  shared_preferences: ^2.5.4
  # 图片选择器 (相册/拍照 - 用于选头像)
  image_picker: ^1.0.7
  # 图片裁切 (用于头像裁切)
  image_cropper: ^8.0.2
  # 颜色提取器 (Monet取色核心 - 从头像提取主题色)
  palette_generator: ^0.3.3

  # --- 工具 ---
  # 格式化时间 (用于"更新于刚刚"等显示)
  intl: any

  share_plus: ^12.0.1      # 用于分享文件
  archive: ^4.0.7         # 用于 ZIP 打包 (为全量备份做准备，也可以用于 epub)

  flutter_file_dialog: ^3.0.2  # 【新增】用于调用系统原生“另存为”
  window_manager: ^0.5.1

  # 【核心新增】：引入商业级富文本排版引擎
  flutter_quill: ^11.5.0

  # 局域网同步战役专属依赖
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^5.0.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6   # (或最新版)
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 代码规范检查
  flutter_lints: ^3.0.0

  # --- 代码生成器 (必须放在 dev_dependencies) ---
  # 通用代码生成运行器
  build_runner: ^2.4.9
  # Isar 数据库代码生成器 (必须与 isar 版本匹配)
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/